import {
  BadgeCheck,
  Building2,
  Factory,
  Gift,
  Handshake,
  Lightbulb,
  MapPin,
  MessageCircle,
  Paintbrush,
  Printer,
  ScanLine,
  ShieldCheck,
  Sparkles,
  Stamp,
  Trophy,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const company = {
  name: "Shivrudra Graphics Pvt Ltd",
  mark: "SG",
  tagline: "Designing | Printing | Branding",
  descriptor:
    "Commercial, Industrial, Corporate Printing and LED Sign Board Manufacturers",
  whatsappNumber: "919075285858",
  phoneDisplay: "+91 9075 28 5858",
  phones: ["+91 9075 28 5858", "+91 9657 44 9996", "+91 9067 17 5858"],
  email: "info@shivrudragraphics.com",
  website: "www.shivrudragraphics.com",
  officeAddress:
    "Shop No. 10, Ground Floor, K.B. Plaza, Opp. Nivaan Meadows, Kesnand-Wagholi Road, Kesnand, Wagholi, Pune 412 207",
  factoryAddress:
    "53/3, Gawthan, Kolwadi, Tal. Haveli, Dist. Pune 412110",
  directors: ["Aadesh C. Nimbalkar", "Akshay N. Kalbhor"],
};

export type CataloguePage = {
  slug: string;
  navLabel: string;
  title: string;
  eyebrow: string;
  summary: string;
  icon: LucideIcon;
  accent: string;
  highlights: string[];
  products?: string[];
  materials?: string[];
  stats?: { value: string; label: string }[];
  sections?: { title: string; items: string[] }[];
};

export const workProcess = [
  "Lead",
  "Inspection",
  "Estimate",
  "Design",
  "Print",
  "Production",
  "Fabrication",
  "Delivery",
  "Installation",
  "Feedback",
];

export const timeline = [
  { year: "2014", name: "Chintamani Arts" },
  { year: "2016", name: "Shivrudra Design" },
  { year: "2019", name: "Shivrudra Graphics" },
  { year: "2026", name: "Shivrudra Graphics Pvt Ltd" },
];

export const industries = [
  "Agriculture",
  "Education",
  "Wholesale Trade",
  "Mining",
  "Home Builders",
  "Automotive",
  "Retail",
  "Manufacturing",
  "Construction",
  "Food & Beverage",
  "Cosmetics",
  "Health Care",
  "Government",
  "Event",
  "Waste Management",
  "Bank",
  "Infrastructure",
  "IT",
  "Hotel",
  "Engineering",
  "Pharmaceuticals",
  "Telecom",
  "Shipping",
  "Insurance",
  "Tourism",
  "Advertising & Media",
  "Bakery",
  "Land Developers",
  "Decorator",
  "Schools & Colleges",
];

export const clients = [
  "Bank of India",
  "IndianOil",
  "HP",
  "DexGreen India",
  "Sunteck Hi-Tech",
  "Pirajees",
  "Bhagylakshmi Group",
  "Sahuwala Cereals",
  "Agrovan",
  "Cherise",
  "Sarvadnya Electro Tech",
  "Sadhu Vaswani Gurukul",
  "Bharat Global School",
  "Acute Innovation",
  "RedRagon",
  "Shreyash Banquets",
  "Caramellas",
  "Circuit House",
  "GURU",
  "Lexicon IHM",
  "JSFM",
  "Edumont Juniors",
  "Sharpedge",
  "Autopeepal",
  "Gravotech",
  "Bettinelli",
  "EMobiliti Systems",
  "DAN Hydraulics",
  "Rainbow Child & Chest Care Center",
  "Apollo Gauging Pvt Ltd",
  "Shree Lifecare Hospital",
  "Shri Hospital",
  "Serum Institute of India",
];

export const pages: CataloguePage[] = [
  {
    slug: "about-us",
    navLabel: "About",
    title: "We are glad to have earned the trust of a strong customer base in Maharashtra.",
    eyebrow: "Company Introduction",
    summary:
      "Originally founded in 2014 at Kesnand and Kolwadi, Shivrudra Graphics now operates from Pune, Maharashtra with complete designing, printing, branding, and LED sign board manufacturing capabilities.",
    icon: Building2,
    accent: "red",
    highlights: [
      "Complete signage solutions from concept to installation",
      "Commercial, industrial, and corporate printing expertise",
      "In-shop branding solutions for businesses and institutions",
      "Directors: Aadesh C. Nimbalkar and Akshay N. Kalbhor",
    ],
    stats: [
      { value: "2014", label: "Founded" },
      { value: "30+", label: "Industries served" },
      { value: "Pune", label: "Maharashtra, India" },
    ],
  },
  {
    slug: "vision-mission-values",
    navLabel: "Vision",
    title: "Vision, mission, and values that keep every print job accountable.",
    eyebrow: "Purpose",
    summary:
      "Shivrudra Graphics aims to help clients grow through reliable graphics solutions, trusted partnerships, and business-focused execution.",
    icon: Lightbulb,
    accent: "yellow",
    highlights: [
      "Vision: provide graphics solutions that increase client growth",
      "Mission: become the most valued business partner for clients",
      "Values: Integrity, Innovation, Team Work, Environment-Friendly, Respect for People",
    ],
    sections: [
      {
        title: "Our Vision",
        items: [
          "Provide all types of graphics solutions to increase the growth of clients.",
          "Build inclusive partnerships based on trust and mutual respect.",
        ],
      },
      {
        title: "Our Mission",
        items: [
          "Be the most valued business partner of every client.",
          "Help clients grow their business and achieve business goals.",
        ],
      },
      {
        title: "Our Values",
        items: [
          "Integrity",
          "Innovation",
          "Team Work",
          "Environment-Friendly",
          "Respect for People",
        ],
      },
    ],
  },
  {
    slug: "commitment-timeline",
    navLabel: "Timeline",
    title: "Started with a vision of establishing business brands.",
    eyebrow: "Our Commitment",
    summary:
      "Driven by innovation, the company evolved from Chintamani Arts to Shivrudra Graphics Pvt Ltd while expanding its print, signage, and branding capabilities.",
    icon: Sparkles,
    accent: "purple",
    highlights: [
      "A business built around innovation and brand establishment",
      "A practical growth story across design, graphics, and manufacturing",
      "Long-term commitment to customer satisfaction from day one",
    ],
  },
  {
    slug: "why-choose-us",
    navLabel: "Why Us",
    title: "A dedicated team for quality branding work and on-time delivery.",
    eyebrow: "Why Choose Shivrudra",
    summary:
      "The team handles design, printing, production, fabrication, delivery, installation, and feedback with complete customer satisfaction as the first priority.",
    icon: BadgeCheck,
    accent: "green",
    highlights: [
      "Customer Satisfaction is Our First Priority",
      "Transparent Communication",
      "Premium Quality Products",
      "Reliable & Professional Service",
      "On-Time Delivery Commitment",
      "High-Quality Printing Solutions",
      "Advanced & Modern Technology",
      "Skilled & Experienced Team",
      "Bulk Order Capability",
      "Creative & Unique Design Approach",
      "Complete End-to-End Printing Solutions",
      "Strong Brand Identity Support",
    ],
  },
  {
    slug: "industries-we-serve",
    navLabel: "Industries",
    title: "Printing and branding support for more than 30 business categories.",
    eyebrow: "Industries We Serve",
    summary:
      "From agriculture and manufacturing to education, healthcare, hospitality, and infrastructure, Shivrudra supports businesses that need reliable printed communication.",
    icon: Factory,
    accent: "blue",
    highlights: [
      "Industrial and corporate branding",
      "Retail and event visibility",
      "Institutional and healthcare communication",
      "Construction, infrastructure, and safety signage",
    ],
  },
  {
    slug: "designing",
    navLabel: "Designing",
    title: "Design services for brands, packaging, promotions, and signages.",
    eyebrow: "Creative Studio",
    summary:
      "A VistaPrint-style starting point for logos, stationery, brochures, flyers, banners, packaging labels, social media creatives, and signage designs.",
    icon: Paintbrush,
    accent: "pink",
    highlights: [
      "Brand identity and logo systems",
      "Print-ready brochure, flyer, poster, and banner artwork",
      "Packaging labels, stickers, and social media creatives",
      "Vehicle wrap and LED signage layouts",
    ],
    products: [
      "Logos",
      "Calligraphy & Vector Art",
      "Business Cards",
      "Letterhead Design",
      "Brochures Design",
      "Flyers Design",
      "Posters Design",
      "Banners Design",
      "Certificates Design",
      "Invitation Cards",
      "Car Wrap Design",
      "LED Signages Design",
      "Social Media Creatives",
      "Product Packaging Labels & Stickers Design",
    ],
    materials: ["Brand brief", "Print-ready artwork", "Editable source file", "Mockup preview"],
  },
  {
    slug: "solvent-eco-solvent-printing",
    navLabel: "Solvent",
    title: "Large-format solvent and eco-solvent printing for outdoor visibility.",
    eyebrow: "Large Format Printing",
    summary:
      "Browse banners, flex, vinyl, standees, wallpapers, car branding, cutouts, exhibition backdrops, and more with WhatsApp-first order details.",
    icon: Printer,
    accent: "orange",
    highlights: [
      "Outdoor and indoor large-format print support",
      "Flex, vinyl, fabric, canvas, and backlit media",
      "Retail, exhibition, vehicle, and site branding formats",
      "Useful for urgent promotional and industrial visibility jobs",
    ],
    products: [
      "Flex Printing",
      "Black Back Flex",
      "Star Flex",
      "Backlit Flex",
      "Vinyl with Foam",
      "Flex with Wooden Frame",
      "Self-Adhesive Vinyl Prints",
      "Glass Filming",
      "Frosted/Office Film",
      "Floor Graphics Printing",
      "Tabletop Printing",
      "Exhibition Backdrops",
      "Cutout Standees",
      "One Way Vision",
      "Redium Sticker",
      "UV Print",
      "Fabric Print",
      "Canvas Print",
      "Transparent Vinyl",
      "Retro Vinyl",
      "Vinyl Print & Cut",
      "Night Glow Vinyl",
      "Translit",
      "Rollup Standy",
      "Sunpack",
      "Canopy Stand",
      "Sunboard Standee",
      "Car Branding",
      "Wallpaper Printing",
      "Graffiti Wall Print",
      "Entry Gate",
      "MS Standy",
    ],
    materials: ["Flex", "Vinyl", "Backlit media", "Canvas", "Sunboard", "Fabric"],
  },
  {
    slug: "digital-printing",
    navLabel: "Digital",
    title: "Digital printing for cards, labels, stickers, tickets, and custom cuts.",
    eyebrow: "Digital Print Shop",
    summary:
      "Short-run and customized print products for labels, certificates, tags, menus, coupons, stickers, wristbands, danglers, PVC cards, and more.",
    icon: Printer,
    accent: "teal",
    highlights: [
      "Small and medium quantity customization",
      "Sticker, label, tag, card, and coupon formats",
      "Half cutting, die cutting, and shaped output support",
      "Useful for retail, events, packaging, and operations",
    ],
    products: [
      "12x18/A4 Print",
      "Texture Paper",
      "NT Paper & NT Sticker",
      "Transparent Sticker",
      "Sticker Paper + Half Cutting",
      "Product Label Printing",
      "Any Shape Full Die Cutting",
      "Tags Printing",
      "Coupon Printing",
      "Wristband Printing",
      "Certificate Printing",
      "Tent Cards",
      "Invitation Card Printing",
      "Menu Card",
      "Danglers Printing",
      "Barcode Sticker",
      "Safety Signage Posters",
      "Door Hangers",
      "Vehicle Parking Stickers",
      "Cable Tag Printing",
      "Roll Labels Printing",
      "Label Printing",
      "Pawati Book Printing",
      "Gift Voucher",
      "Packaging Sticker",
      "Packaging Sleeves",
      "Wrapping Paper",
      "Custom Car Stickers",
      "Seal Stickers",
      "Ticket Printing",
      "Rack Card",
      "Bookmark Printing",
      "PVC Cards",
      "ID Card Printing",
      "Lanyard Printing",
      "Header Cards",
      "Shelf Wobblers",
      "Bottle Neck Tags",
      "Swing Tags",
      "Photo Frame",
      "Ribbon Batch",
      "Tree Tag",
      "Cloth Tag",
      "Cutout",
    ],
    materials: ["Art paper", "Texture paper", "Sticker media", "PVC", "Transparent film"],
  },
  {
    slug: "offset-printing",
    navLabel: "Offset",
    title: "Offset printing for business stationery, books, bags, and catalogues.",
    eyebrow: "Offset Printing",
    summary:
      "Professional bulk printing for business cards, envelopes, brochures, leaflets, letterheads, forms, files, books, calendars, and bags.",
    icon: Printer,
    accent: "navy",
    highlights: [
      "Bulk print capability for corporate and institutional work",
      "Stationery, files, reports, books, and catalogue products",
      "Suitable for consistent brand systems and repeated operations",
      "Designed for clean production planning through WhatsApp enquiry",
    ],
    products: [
      "Business Card Printing",
      "Envelope Printing",
      "Brochure Printing",
      "Leaflet Printing",
      "Letterhead Printing",
      "Register Printing",
      "Bank Form Printing",
      "File Printing",
      "Hospital File Printing",
      "Pocket Folder",
      "Prescription Pad",
      "Medical Pouch",
      "Calendar Printing",
      "Diary Printing",
      "Parking Valet Card",
      "Cardsheet Printing",
      "Bill Book Printing",
      "Receipt/DC Book Printing",
      "Notebooks",
      "Sticker Roll Printing",
      "Product Catalogue",
      "Nonwoven Bags",
      "Book Printing",
      "Table Calendar",
      "Paper Bag",
      "Catalogue Printing",
      "Note Pads Printing",
      "Synthetic Tags",
      "Report Printing",
    ],
    materials: ["Art paper", "Maplitho", "Card sheet", "Synthetic tag", "Nonwoven"],
  },
  {
    slug: "stamps-screen-pad-printing",
    navLabel: "Stamps",
    title: "Stamps, screen printing, and pad printing for industrial surfaces.",
    eyebrow: "Special Printing",
    summary:
      "Specialized printing for stamps, polycarbonate labels, metal tags, boxes, textiles, glass, wood, industrial objects, automotive and electrical components.",
    icon: Stamp,
    accent: "brown",
    highlights: [
      "Rubber, dater, numbering, and branded stamp options",
      "Screen printing across metal, plastic, glass, textile, and wooden surfaces",
      "Pad printing for industrial, automotive, cosmetics, and appliance objects",
      "Useful for technical marking, packaging, and component branding",
    ],
    products: [
      "Plus Stamp",
      "Sun Stamp",
      "Colop Numbering Stamp",
      "Colop Dater Stamp",
      "Dolphin Dater Stamp",
      "Dolphin Numbering",
      "Trodat Stamp",
      "Colop Mouse Stamp",
      "Small Rubber Stamp",
      "Big Rubber Stamp",
      "Stamp Pad",
      "Polycarbonate Labels & Sticker",
      "Metal QR Code Tags",
      "Sunpack Printing",
      "Bag Printing",
      "Aluminium Name Plates",
      "Bottle Printing",
      "MS/SS Screen Printing",
      "Plastic Crate",
      "Vinyl Printing",
      "Redium Printing",
      "Polyester Printing",
      "PP Box",
      "Corrugated Box",
      "Textile Printing",
      "Glass Printing",
      "Wooden Printing",
      "Automotive Pad Printing",
      "Electrical Component Pad Printing",
      "Cosmetics Pad Printing",
      "White Goods Pad Printing",
    ],
    materials: ["Rubber", "Metal", "Plastic", "Polycarbonate", "Glass", "Textile"],
  },
  {
    slug: "badges-stickers-keychains",
    navLabel: "Badges",
    title: "Badges, dome stickers, keychains, and epoxy brand pieces.",
    eyebrow: "Brand Accessories",
    summary:
      "Custom acrylic, metal, aluminium, SS, dome, epoxy, button, magnet, name badge, and keychain products for identity and promotion.",
    icon: ShieldCheck,
    accent: "red",
    highlights: [
      "Epoxy and dome finishing for premium brand recall",
      "Acrylic, SS, aluminium, metal, and rexine options",
      "Badges and keychains for events, staff, clients, and merchandise",
      "Low-friction WhatsApp order flow for size and quantity details",
    ],
    products: [
      "Dome Sticker",
      "SS Dome Sticker",
      "Dome Keychain",
      "Acrylic Keychain",
      "Acrylic Shape Cut Epoxy Badges",
      "SS Metal Epoxy Badges",
      "Acrylic Epoxy Badges",
      "LOGO Acrylic Epoxy Badges",
      "Aluminium Epoxy Badges",
      "Round Metal Epoxy Badges",
      "SS Keychain",
      "Keychain Badge",
      "Pin Button Badges",
      "Magnet Button Badges",
      "Name Badges",
      "Rexine Leather Keychain",
    ],
    materials: ["Acrylic", "SS", "Aluminium", "Metal", "Epoxy", "Rexine"],
  },
  {
    slug: "corporate-gifts",
    navLabel: "Gifts",
    title: "Corporate gifts and employee kits with custom printing.",
    eyebrow: "Corporate Gifts",
    summary:
      "Branded mugs, caps, T-shirts, mousepads, flasks, pens, diaries, tumblers, card holders, stands, safety prints, and welcome kits.",
    icon: Gift,
    accent: "yellow",
    highlights: [
      "Custom gift products for employees, clients, and events",
      "Welcome kit support for onboarding and campaigns",
      "Brand print options across fabric, metal, plastic, and accessories",
      "WhatsApp enquiry captures quantity, artwork, and delivery timeline",
    ],
    products: [
      "Mug Printing",
      "Cap Printing",
      "T-shirt Printing",
      "Mousepad Printing",
      "Flasks",
      "Pen Printing",
      "Diaries",
      "Tumblers",
      "Card Holder",
      "Reflective Safety Printing",
      "Mobile/Laptop Stand",
      "Employee Welcome Kit",
    ],
    materials: ["Ceramic", "Fabric", "Metal", "Plastic", "Paper", "Reflective"],
  },
  {
    slug: "engraving-marking",
    navLabel: "Engraving",
    title: "Laser engraving and marking for metal, plastic, leather, and tools.",
    eyebrow: "Engraving & Marking",
    summary:
      "Precision identification and branding for plates, components, labels, QR codes, tools, leather, polymer material, and industrial parts.",
    icon: ScanLine,
    accent: "green",
    highlights: [
      "Industrial marking for traceability and safety",
      "Gold, silver, SS, anodised aluminium, ABS, and traffolite outputs",
      "QR code and machine-readable marking support",
      "Suitable for manufacturing, hardware, automobile, and utility use",
    ],
    products: [
      "Gold/Silver Laser Etched Plates",
      "ABS Plastic Marking",
      "Automobile Parts",
      "Metal Parts Marking",
      "Anodised Aluminium Plates",
      "SS Etching Plate",
      "Traffolite Signage",
      "Leather Marking",
      "QR Code",
      "Black Stainless Marking",
      "Bulb Marking",
      "Watch Case",
      "SS Marking",
      "Hardware Tool Marking",
      "Polymer Material",
    ],
    materials: ["SS", "Aluminium", "ABS", "Leather", "Polymer", "Traffolite"],
  },
  {
    slug: "signages",
    navLabel: "Signages",
    title: "Standard signages, LED letters, acrylic boards, and display systems.",
    eyebrow: "Signage Manufacturing",
    summary:
      "End-to-end signage solutions covering standees, foam boards, pylon signage, backlit boards, acrylic frames, LED signage, SS letters, folders, and customized boxes.",
    icon: MapPin,
    accent: "blue",
    highlights: [
      "Concept, design, manufacturing, delivery, and installation support",
      "Indoor, outdoor, lobby, industrial, and retail signage formats",
      "Acrylic, MS, SS, LED, ACP, foam, fabric, and magnetic solutions",
      "Built for local businesses, institutions, factories, and shops",
    ],
    products: [
      "Standee Signage",
      "Sunboard Foam Board",
      "Foam Sign Board",
      "Pylon Signage",
      "Fabric Signage",
      "Backlit Board Signage",
      "Aluminium Clip-on Frame",
      "Night Glow Signage",
      "Acrylic Sandwich Frame",
      "White Board & Stand",
      "2D LED Signage",
      "Easel Stands",
      "Magnetic Signage",
      "3D LED Signage",
      "SS Letter Signage",
      "Acrylic Letter",
      "MS Letter Signage",
      "Sparkling/Crystal Signage",
      "Profile Bending Signage",
      "Liquid Letter Signage",
      "Lobby Sign Signage",
      "Retro Sign Signage",
      "Scrolling Signage",
      "Industrial Display Signage",
      "Acrylic Folder Signage",
      "Acrylic Magnetic Folder",
      "Acrylic Name Board Signage",
      "Acrylic First Aid Box",
      "Acrylic Suggestion Box",
      "Acrylic Customized Box",
      "ACP Gate Signage",
      "MS Frame + Backlight",
      "Reverse Printed Acrylic Frames",
    ],
    materials: ["Acrylic", "ACP", "MS", "SS", "LED", "Foam board", "Fabric"],
  },
  {
    slug: "premium-safety-signages",
    navLabel: "Safety",
    title: "Premium nameplates, awards, wayfinding, and safety signage.",
    eyebrow: "Premium & Safety Signages",
    summary:
      "Wayfinding signs, directory signs, table tops, nameplates, awards, acrylic signs, safety signs, mandatory signs, emergency exits, warning signs, and road signs.",
    icon: ShieldCheck,
    accent: "orange",
    highlights: [
      "Premium sign systems for offices, homes, lobbies, and institutions",
      "Mandatory, warning, fire, prohibition, recycle, and road signage",
      "Photoluminescent and safety floor sign options",
      "Useful for factories, schools, hospitals, and public spaces",
    ],
    products: [
      "Way Finding Sign",
      "Free Hand Sign",
      "Directory Sign",
      "Table Top",
      "Flat Home Nameplate",
      "Plaque",
      "Awards",
      "Hangers",
      "3D Signs",
      "2D Signs",
      "Acrylic Sign",
      "Table Name Plate",
      "Safety Signages",
      "Mandatory Safety Signage",
      "Emergency Exit",
      "Wear Safety Helmet Sign",
      "Warning Signs",
      "Fire Signs",
      "Prohibition Sign",
      "Recycle Signs",
      "Safety Floor Signs",
      "Road Signs",
      "Photoluminescent Signs",
      "No Parking Sign",
    ],
    materials: ["Acrylic", "Metal", "Photoluminescent", "Vinyl", "ACP", "Reflective"],
  },
  {
    slug: "laser-cnc-ferrule-printing",
    navLabel: "Cutting",
    title: "Laser, CNC, fabrication cutting, and ferrule printing.",
    eyebrow: "Cutting & Wire Marking",
    summary:
      "MDF, ACP, acrylic, MS, SS cutting and engraving alongside wire marker products such as PVC tube, heat shrink tube, and marking strip.",
    icon: Wrench,
    accent: "teal",
    highlights: [
      "Laser and CNC output for sign, decor, and industrial use",
      "MDF, ACP, acrylic, MS, and SS cutting/engraving",
      "Ferrule and wire marker printing for electrical panels",
      "Good fit for fabrication, utility, and signage projects",
    ],
    products: [
      "MDF Cutting",
      "MDF Engraving",
      "MDF Pattern Cutting",
      "ACP Cutting",
      "Acrylic Jali Cutting",
      "MS/SS Cutting",
      "Acrylic Cutting",
      "Acrylic Engraving",
      "ACP Jali Cutting",
      "PVC Tube Wire Markers",
      "Heat Shrink Tube",
      "Marking Strip",
      "MS/SS Frames",
      "Display Stands",
      "Retail Display Fabrication",
      "Hoarding Structures",
      "Pylon Fabrication",
    ],
    materials: ["MDF", "ACP", "Acrylic", "MS", "SS", "PVC", "Heat shrink"],
  },
  {
    slug: "trophies-medals-nameplates",
    navLabel: "Awards",
    title: "Trophies, medals, aluminium plates, sublimation, and custom labels.",
    eyebrow: "Awards & Plates",
    summary:
      "Acrylic, wooden, plastic, metal, foil, ABS, flag trophies, cups, medals, anodized aluminium name plates, sublimation frames, and industrial labels.",
    icon: Trophy,
    accent: "purple",
    highlights: [
      "Awards for events, institutions, offices, and recognition programs",
      "Industrial aluminium name plates and color-coded data plates",
      "Sublimation frames, metal cards, warning labels, and caution labels",
      "Designed for both ceremonial and technical requirements",
    ],
    products: [
      "Acrylic Trophies",
      "Wooden Trophies",
      "Plastic Frames",
      "Metal Frame",
      "Foil Trophies",
      "Metal Trophies",
      "ABS Trophies",
      "Flag Trophies",
      "Cups",
      "Medals",
      "Anodized Aluminium Name Plates",
      "Industrial Data Plates",
      "Electrical Labels",
      "Barcode Plates",
      "Danger/Warning Plates",
      "Silver/Golden Certificate",
      "Sublimation Frame",
      "Industrial Label",
      "Metal Business Cards",
      "Deskpads Printing",
      "Fabric Printing",
      "Coaster Printing",
    ],
    materials: ["Acrylic", "Wood", "Metal", "Aluminium", "ABS", "Sublimation blank"],
  },
  {
    slug: "clients",
    navLabel: "Clients",
    title: "Trusted by brands, institutions, healthcare, industry, and education.",
    eyebrow: "Our Clients",
    summary:
      "The brochure showcases a wide client base across banking, oil and energy, schools, healthcare, manufacturing, hospitality, technology, and industrial businesses.",
    icon: Handshake,
    accent: "green",
    highlights: [
      "Banking, energy, healthcare, and education clients",
      "Industrial, hospitality, technology, and manufacturing clients",
      "Client logo area is ready for brochure-extracted brand assets",
      "Current MVP uses protected logo placeholders until final assets are added",
    ],
  },
  {
    slug: "contact",
    navLabel: "Contact",
    title: "Send an enquiry, order request, or complaint through WhatsApp.",
    eyebrow: "Connect With Us",
    summary:
      "Ask about products, features, trials, pricing, complaints, or anything else. The MVP opens WhatsApp with structured details so the Shivrudra team can respond quickly.",
    icon: MessageCircle,
    accent: "red",
    highlights: [
      company.officeAddress,
      company.factoryAddress,
      `${company.phoneDisplay} | +91 9657 44 9996 | +91 9067 17 5858`,
      company.email,
    ],
  },
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/enquiry", label: "Enquiry" },
  ...pages.map((page) => ({ href: `/${page.slug}`, label: page.navLabel })),
];

export const servicePages = pages.filter((page) => page.products?.length);

export const allProducts = servicePages.flatMap((page) =>
  (page.products ?? []).map((product) => ({
    product,
    service: page.title,
    slug: page.slug,
    accent: page.accent,
  })),
);
